### ISSUE TITLE
Addon causes build error

### ISSUE THREAD

**Issue by jeffdaley** [ember-animation/ember-animated-tools#150]
When I install this and run `yarn build` I get an error:

```
Build Error (Inserter)

ember-auto-import could not find a place to insert app styles in index.html
```

Any ideas on how to fix? Thanks 🙏

**Comment by ef4** [comment]
ember-auto-import is looking for [this line](https://github.com/ember-cli/ember-new-output/blob/e03dae32dd10a2637537538dc7458934b6b70d85/app/index.html#L12) in your index.html. If you've got something nonstandard there, that would be the reason. The standard CSS file is named to match your app's name.

If you need to customize beyond the defaults you can do that too, following the instructions in [Customizing HTML Insertion](https://github.com/embroider-build/ember-auto-import#customizing-html-insertion).

**Comment by jeffdaley** [comment]
Thanks for pointing me in the right direction.

Turns out it was `vendor.css` that the addon needed, and my app didn't have it linked. Nonstandard !

```
// app/index.html
// Adding this fixed it
<link integrity="" rel="stylesheet" href="{{rootURL}}assets/vendor.css" />
