### ISSUE TITLE
`ember-animated-tools` compatible with ember-animated v2.0.0 not published to npm yet?

### ISSUE THREAD

**Issue by johanrd** [ember-animation/ember-animated-tools#162]
Hi. Great work on releasing ember-animated v2.0.0!

I see in [`addon/package.json`](https://github.com/ember-animation/ember-animated-tools/blob/master/addon/package.json#L35) that the latest version of `ember-animated-tools` is compatible with `"ember-animated": "^1.0.0 || ^2.0.0",`

yet, when installing `ember-animated-tools`from npm I get `v1.0.0` which still pulls down ember-animated `1.1.3`.

Is `ember-animated-tools` missing a publish to npm? 
thanks,

**Comment by SergeAstapov** [comment]
@johanrd this is now completed see https://github.com/ember-animation/ember-animated-tools/releases/tag/v2.0.0 and https://www.npmjs.com/package/ember-animated-tools
