### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by samselikoff** [ember-animation/ember-animated-tools#3]
Just adding `{{animated-tools}}` isn't working for me...

**Comment by ef4** [comment]
That's supposed to be all you need. I would suspect some CSS is hiding them.

**Comment by samselikoff** [comment]
Believe some bad logic might have gotten in through https://github.com/ember-animation/ember-animated-tools/commit/8e3285da0a5ba1048b305303eabd7538fc6dca39.

For now I'm rendering 

```hbs
<AnimatedTools @isHidden={{false}} />
```

**Comment by ef4** [comment]
You're right, that's backwards.

**Comment by ef4** [comment]
Should be fixed in 0.4.1 now.

**Comment by Turbo87** [comment]
@ef4 does this addon deactivate itself for production builds or is that the responsibility of the user? can't find any clues in the README or the code 🤔

**Comment by ef4** [comment]
It doesn't. I'm fine with taking a PR to add that capability. Though I hope the days of manually needing to do things like that inside addons are coming to an end.
