### ISSUE TITLE
Uncaught ReferenceError: Ember is not defined

### ISSUE THREAD

**Issue by ShaneON** [ember-animation/ember-animated-tools#74]
I'm getting an error when trying to run the tools, using latest ember version 4.1.0.

Error is: `Uncaught ReferenceError: Ember is not defined`. 

And it looks like its coming from: `var _default = Ember.HTMLBars.template({
    "id": "NJJ4r4MM",
    "block": "[[[41,[51,[30,0,[\"isHidden\"]]],[[[1,\"  \"],[11,0],[16,0,[29,[\"animated-tools \",[52,[30,0,[\"isOpen\"]],\"is-open\"]]]],[17,1],[12],[1,\"\\n    \"],[11,0],[24,0,\"animated-tools-launcher\"],[4,[38,2],[[30,0],\"toggle\"],null],[12],[1,\"\\n      \"],[1,[34,3]],[1,\"\\n      ⏱\"],[1,\"\\n    \"],[13],[1,\"\\n    \"],[10,0],[14,0,\"animated-tools-panel\"],[12],[1,\"\\n      \"],[1,[34,4]],[1,\"\\n    \"],[13],[1,\"\\n  \"],[13],[1,\"\\n\"]],[]],null]],[\"&attrs\"],false,[\"unless\",\"if\",\"action\",\"motion-indicator\",\"time-control\"]]",
    "moduleName": "ember-animated-tools/templates/components/animated-tools.hbs",
    "isStrictMode": false
  });`

**Reproducing bug**

Start a new ember project using version 4.1.0, install ember-animated and ember-animated-tools, add `<AnimatedTools />` component to `application.hbs` and run the server.

Thanks

**Comment by ef4** [comment]
@SergeAstapov I think you have already done the work to fix this on master, is this ready to release?

**Comment by SergeAstapov** [comment]
@ef4 yes, I think we should be good to do a release for this addon

**Comment by ef4** [comment]
Published 0.5.0, which fixes this issue.
